// Author: Alessandro Trigolo

#ifndef BATTAGLIA_NAVALE_INCLUDE_BATTLESHIP_GAMEMODE_H_
#define BATTAGLIA_NAVALE_INCLUDE_BATTLESHIP_GAMEMODE_H_
enum GameMode { COMPUTER_VS_COMPUTER,
				COMPUTER_VS_HUMAN,
				REPLAY };
#endif//BATTAGLIA_NAVALE_INCLUDE_BATTLESHIP_GAMEMODE_H_
